# Site settings
title: kblog
# tagline: "Changing the world, one uninspired quote at a time"
url: "http://kaljr.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
# socialimg: /img/social.jpg # be sure to change this image
# facebook: fbusername
# twitter: twusername
github: kaljr
# googleplus: gusername
instagram: kepsolotl

# Contact
# phone: "916-276-1044" # This is my real number. You should text me.
email: "kenny.langston@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

theme: jekyll-theme-merlot
